management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
server:
    compression:
        enabled: true
        mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
        min-response-size: 2048
    port: 8080

spring:
    application:
        name: customer-service
    data:
        mvc:
            resources:
                add-mappings: false
            throw-exception-if-no-handler-found: true
        thymeleaf:
            check-template-location: false
        web:
            pageable:
                max-page-size: 100
                page-parameter: 'page '
                size-parameter: 'size '
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: false
                show_sql: false
                type: trace
                use_sql_comments: false
    datasource:
        password: postgres
        url: jdbc:postgresql://localhost:5432/travels
        username: postgres


api:
    key: '"TEST-API"'
    version: '2020-12-29'